### PR TITLE
Starter code for bot

### PR DESCRIPTION
**Pull request by GreyWolfSif**

### CODE REVIEW

**Comment by GreyWolfSif** [comment]
Test comment (I'm new lol)

**Comment by geraldjet** [comment]
yes

**Comment by jason2208** [comment]
123

**Comment by strawberriesAreGreat** [comment]
uhhhhhhh

**Review by geraldjet — APPROVED** [review]
approved

**Review by strawberriesAreGreat — APPROVED** [review]
Great work me

**Pull request merged**
